repositories:
  - name: aws-eks
    url: https://aws.github.io/eks-charts

  - name: bjw-s
    url: https://bjw-s.github.io/helm-charts

  - name: gpu-operator
    url: https://nvidia.github.io/gpu-operator

  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

helmDefaults:
  createNamespace: true
  wait: true
  waitForJobs: true
  deleteWait: true
  timeout: 7200  # = 2h; includes triton-client job
  deleteTimeout: 600

releases:
  - name: gpu-operator
    namespace: gpu-operator
    chart: gpu-operator/gpu-operator
    version: 24.6.1
    values:
      - values/gpu-operator.yaml

  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 61.9.0
    values:
      - values/kube-prometheus-stack.yaml.gotmpl

  - name: prometheus-adapter
    namespace: monitoring
    chart: prometheus-community/prometheus-adapter
    version: 4.11.0
    values:
      - values/prometheus-adapter.yaml

  - name: aws-for-fluent-bit
    namespace: monitoring
    chart: aws-eks/aws-for-fluent-bit
    version: 0.1.34
    needs:
      - monitoring/kube-prometheus-stack  # ServiceMonitor CRD
    values:
      - values/aws-for-fluent-bit.yaml.gotmpl

  - name: triton-server
    namespace: triton-server
    chart: bjw-s/app-template
    version: 3.3.2
    needs:
      - gpu-operator/gpu-operator  # GPU
      - monitoring/kube-prometheus-stack  # ServiceMonitor CRD
    values:
      - values/triton-server.yaml.gotmpl

  - name: triton-client
    namespace: triton-client
    chart: bjw-s/app-template
    version: 3.3.2
    needs:
      - triton-server/triton-server
    values:
      - values/triton-client.yaml.gotmpl
